routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 Route::get('/','admin\LoginController@showloginform')->name('showloginform')->middleware('AuthRedirect');

// Auth::routes();
 Route::post('/login','admin\LoginController@login')->name('admin.login');
 Route::post('/logout','admin\LoginController@logout')->name('admin.logout');

 Route::get('/home', 'HomeController@index')->name('admin.dashboard.home')->middleware('Admin');
 Route::post('/EditProfile/{id}','HomeController@edit')->name('editprofile');

 Route::namespace('admin')->name('admin.')->middleware('Admin')->group(function()
{      
        //Students Routes//
        Route::get('/AddStudents', 'students\studentsController@create')->name('students.create');
        Route::get('/ShowStudents', 'students\studentsController@index')->name('students.index');
        Route::get('/ajax/getprogram','students\studentsController@findprogram');
        Route::post('/Students/store', 'students\studentsController@store')->name('students.store');
        Route::get('/ViewStudents/{student}', 'students\studentsController@view')->name('students.view');
        Route::get('/DeleteStudent/{id}', 'students\studentsController@destroy')->name('students.destroy');
        Route::get('/EditStudent/{id}', 'students\studentsController@edit')->name('students.edit');
        Route::post('/UpdateStudent/{id}', 'students\studentsController@update')->name('students.update');
        Route::post('/SearchStudents','students\studentsController@search')->name('students.search');



        //Notice Routes//
         Route::get('/AddNotice' ,'notice\noticeController@create')->name('notice.create');
         Route::get('/ViewNotices' ,'notice\noticeController@index')->name('notice.index');
         Route::post('PostNotice/store','notice\noticeController@store')->name('notice.store');
         Route::get('/EditNotice/{id}','notice\noticeController@edit')->name('notice.edit');
         Route::post('/UpdateNotice/{id}','notice\noticeController@update')->name('notice.update');
         Route::get('/DeleteNotice/{id}','notice\noticeController@destroy')->name('notice.destroy');


         //Assignment Routes//
         Route::get('/AddAssignment','assignment\assignmentController@create')->name('assignment.create');
         Route::get('/ShowAssignment','assignment\assignmentController@index')->name('assignment.index');
         Route::post('/PostAssignment/store','assignment\assignmentController@store')->name('assignment.store');
         Route::post('/SearchAssignment','assignment\assignmentController@searchassignment')->name('assignment.searchassignment');
         Route::get('/EditAssignment/{id}','assignment\assignmentController@edit')->name('assignment.edit');
         Route::post('/udateAssignment/{id}','assignment\assignmentController@update')->name('assignment.update');
         Route::get('/DeleteAssignment/{id}','assignment\assignmentController@destroy')->name('assignment.destroy');


        //Courses Routes//
        Route::get('/AddCourses','courses\coursesController@create')->name('courses.create');
        Route::get('/ShowCourses','courses\coursesController@index')->name('courses.index');
        Route::post('/StoreCourseCatogery/store','courses\coursesController@store')->name('courses.store');
        Route::post('/SearchCourseCatogey','courses\coursesController@searchtoinsertcourse')->name('courses.searchtoinsertcourse');
        Route::get('/ShowSubjectFields/{id}','courses\coursesController@showsubject')->name('courses.subject');
        Route::post('/StoreSubject/store','courses\coursesController@storesubject')->name('courses.storesubject');
        Route::get('/DeleteSubject/{id}','courses\coursesController@destroy')->name('courses.destroy');



        //Marks Routes//
        Route::get('/ShowMarks','marks\MarksController@searchmarks')->name('marks.view');
        Route::post('ViewMarks','marks\MarksController@viewmarks')->name('marks.searchmarks');
        Route::get('/InsertMarks','marks\MarksController@index')->name('marks.index');
        Route::post('/AddMarks','marks\MarksController@showmarksform')->name('marks.addmarks');
        Route::post('/Store/Marks','marks\MarksController@store')->name('marks.store');
        Route::Post('/EditMarks','marks\MarksController@edit')->name('marks.edit');
        Route::post('/UpdateMarks/Update','marks\MarksController@updatemarks')->name('marks.update');




        //Teachers Routes//
        Route::get('/AddTeachers','Teachers\teachersController@create')->name('teachers.create');
        Route::get('/ShowTeachers','Teachers\teachersController@index')->name('teachers.index');
        Route::post('PostTeachers/store','Teachers\teachersController@store')->name('teachers.store');
        Route::get('Teachers/destroy/{id}','Teachers\teachersController@destroy')->name('teachers.destroy');
        
        //Faculty Routes//
        Route::get('/AddFaculty','faculty\facultyController@create')->name('faculty.create');
        Route::get('/ShowFaculty','faculty\facultyController@index')->name('faculty.index');
        Route::post('/AddFaculty/store','faculty\facultyController@store')->name('faculty.store');
        Route::get('/EditFaculty/{faculty_id}','faculty\facultyController@edit')->name('faculty.edit');
        Route::post('/UpdateFaculty/{faculty_id}','faculty\facultyController@update')->name('faculty.update');
        Route::get('/DeleteFaculty/{faculty_id}','faculty\facultyController@destroy')->name('faculty.destroy');

        //Program Routes//
        Route::get('/AddProgram','program\programController@create')->name('program.create');
        Route::get('/ShowProgram','program\programController@index')->name('program.index');
        Route::post('/AddProgram/store','program\programController@store')->name('program.store');
        Route::get('/EditProgram/{program_id}','program\programController@edit')->name('program.edit');
        Route::post('/UpdateProgram/{program_id}','program\programController@update')->name('program.update');
        Route::get('/DeleteProgram/{program_id}','program\programController@destroy')->name('program.destroy');
        Route::post('/SearchProgram/from/faculty','program\programController@searchprogram')->name('search.program.from.faculty');


        //Symbol Routes//
        Route::get('/AddSymbol','Symbol\SymbolController@create')->name('symbol.create');
        Route::get('/ajax/getprogram','Symbol\SymbolController@findprogram');
        Route::post('/ShowSymbolForm','symbol\SymbolController@symbolnumberform')->name('symbol.showsymbolnumberform');
        Route::post('/SymbolNo/store','symbol\SymbolController@store')->name('symbol.store');
        Route::get('/AllSymbolData','symbol\SymbolController@index')->name('symbol.index');
        Route::post('/SearchSymbolCatogory','symbol\SymbolController@SearhSymbolFaculty')->name('symbol.SearhSymbolFaculty');
        Route::get('/ShowAllSymbol/{symbol_number_category_id}','symbol\SymbolController@symbolview')->name('symbol.viewsymbol');
        Route::get('/EditSymboNumber/{symbol_number_category_id}','symbol\SymbolController@symbolupdate')->name('symbol.symbolupdate');
        Route::post('/UpdateSymbol/store','symbol\SymbolController@symbolupdatestore')->name('symbol.symbolupdatestore');
        

        //Year Routes//
        Route::get('/CreateYear','AdmissionYear\YearController@index')->name('year.index');
        Route::post('/PostYear/store','AdmissionYear\YearController@store')->name('year.store');
        Route::get('/EditYear/{id}','AdmissionYear\YearController@edit')->name('year.edit');
        Route::post('/UpdateYear/{id}','AdmissionYear\YearController@update')->name('year.update');
        Route::get('/DeleteYear/{id}','AdmissionYear\YearController@destroy')->name('year.destroy');


        //user access  and user role control route here
         Route::get('user/role','UserRoleController@index')->name('user.role');
         Route::get('user/role/create','UserRoleController@create')->name('create.user.role');
         Route::post('user/role/store','UserRoleController@store')->name('store.user.role');
         Route::get('user/access/show/{role_id}','UserAccessController@show')->name('show.user.access');
         Route::post('user/access/store','UserAccessController@store')->name('store.user.access');

         //Register for role id password//
         Route::get('user/register','RoleRegisterController@roleregisterform')->name('role.register.form');
         Route::post('user/register/store','RoleRegisterController@store')->name('role.register.store');


});



//FontEnd Page Routes//
Route::get('/EducatSystem','user\UserController@index')->name('user.index');
Route::get('/StudentResult','user\UserController@result')->name('user.result');
Route::post('/MarkSheet/Marks','user\UserController@showmarksheet')->name('user.marksheet');
Route::get('/Notices','user\UserController@notice')->name('user.notice');

app/Marks.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Marks extends Model
{
       protected $fillable=['subject_id','symbol_number_id','marks','symbol_number_catogery_id'];

       protected $table='marks';

       public function programcourse()
       {
        return $this->belongsTo(ProgramCourse::class,'subject_id');
       }
}

resources/views/admin/marks/addmarks.blade.php
@extends('layouts.admin.app')
@section('content')

<section class="content">
        <div class="row">
            <div class="col-md-12">
               @include('layouts.alert')
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Add marks</h3>                   
                       <div class="box-body">
                      <div class="col-md-12  ">
                       
                    
                   <table class="table table-bordered table-striped">
                          <thead class="bg-green"> 
                            <tr>
                                <th style="width: 10px">sn</th>
                             
                                <th>symbol num</th>
                                <th>name</th>
                                @forelse($subjects as $subject)
                                <th>{{$subject->subject_name}}</th>
                                 @empty
                                   <th>no subject</th>
                                @endforelse
                           </tr>
                          </thead>

                           <tbody>
                            <form method="post" action="{{route('admin.marks.store')}}" >
                              @csrf
                           
                              @forelse($symbolNumbers as $symbolNumber)
                               <tr>
                                 <td>{{$loop->iteration}}</td>
                                 <td>{{$symbolNumber->symbol_number}}</td>
                                 <td>{{$symbolNumber->student->name}}</td>

                                    @forelse($subjects as $subject)
                                    <td><input type="text" name="{{$symbolNumber->id}}{{$subject->id}}[mark]">

                                    <input type="hidden" name="{{$symbolNumber->id}}{{$subject->id}}[symbolNumber_id]" value="{{$symbolNumber->id}}">
                                    <input type="hidden" name="{{$symbolNumber->id}}{{$subject->id}}[subject_id]" value="{{$subject->id}}"></td>
                                    <input type="hidden" name="{{$symbolNumber->id}}{{$subject->id}}[symbol_number_category_id]" value="{{$symbol_number_category_id}}">
                                     @empty
                                       <td>no subject</td>
                                     @endforelse
                                 </tr>

                               
                                @empty
                                 <tr>
                                  <td colspan="10"><center>No data found on this <strong>search</strong> </center></td>
                                 </tr>
                                @endforelse

                                <!-- Modal -->

              
                           <tbody>
                          </table>
                         <br>
                       <center> <button type="submit" class=" btn btn-success">Submit</button></center>
                     {{--  @endif --}}
                     </form>
                    </div><!-- /.box-body -->
                  </div>
                </div><!-- /.box -->

            </div><!-- /.col -->
        
    </section><!-- /.content -->


    


@endsection

@section('css')
<style type="text/css">
  .test-file span
{
  font-size: 16px; font-weight: lighter;
}
.margin-style
{
  margin-top: 40px;
}
.profile_student
{
height:120px; width: 120px;
}
.title-s-data
{
  text-decoration: underline;
}
</style>
@endsection


   @section('script')
 

@endsection
 

resources/views/admin/marks/edit.blade.php
@extends('layouts.admin.app')
@section('content')
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box bg-green">
                <div class="box-header">
                    <h3 class="box-title color-white">Edit Marksheet</h3>
                </div><!-- /.box-header -->
            </div>
        </div>
        <div class="col-md-12 size ">
            <div class="float-left">
                <p><strong><span>Faculty:</span></strong> {{$SymbolNumberCategory->faculty->faculty_name}} </p>
                <p><strong><span>Program:</span></strong> {{$SymbolNumberCategory->program->program_name}}</p>
                <p><strong><span>Admision year:<span></strong>{{$SymbolNumberCategory->admissionyear->admission_year}}</p>
            </div>
            <div class="float-right">
                <p><strong><span>Year:<span></strong> {{$SymbolNumberCategory->year->name}}</p>
                <p><strong><span>Semester:<span></strong> {{$SymbolNumberCategory->semester->name}}</p>
                <br>
            </div>
            <form method="post" action="{{route('admin.marks.update')}}">
                @csrf
                <table class="table table-bordered table-striped border">
                    <thead class="bg-green">
                        <tr>
                            <th style="width: 10px">SN</th>
                            <th>Name</th>
                            <th>Symbol_No</th>
                            @forelse($subjects as $subject)
                            <th>{{$subject->subject_name}}</th>
                            @empty
                            <th>no subject</th>
                            @endforelse
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($symbolNumbers as $symbolNumber)
                        <tr>
                            <td>{{$loop->iteration}}</td>
                            <td> {{$symbolNumber->student->name}}</td>
                            <td>{{$symbolNumber->symbol_number}}</td>
                            @forelse($subjects as $subject)
                            <td>
                                @forelse($marks as $mark)
                                @if($mark->subject_id==$subject->id && $mark->symbol_number_id==$symbolNumber->id )
                                <input type="text" name="{{$symbolNumber->id}}{{$subject->id}}[mark]" value="{{ $mark->marks}}">
                                <input type="hidden" name="{{$symbolNumber->id}}{{$subject->id}}[subject_id]" value="{{ $subject->id}}">
                                <input type="hidden" name="{{$symbolNumber->id}}{{$subject->id}}[symbol_id]" value="{{ $symbolNumber->id}}">
                                @endif
                                @empty
                                @endforelse
                            </td>
                            @empty
                            <td>no subject</td>
                            @endforelse
                        </tr>
                        @empty
                        <tr>
                            <td colspan="10">
                                <center>No data found on this <strong>search</strong> </center>
                            </td>
                        </tr>
                        @endforelse
                    <tbody>
                </table>
                <center><button type="submit" class="btn btn-success ">Update</button></center>
            </form>
        </div>
    </div><!-- /.box-body -->
    </div>
    </div><!-- /.box -->
    </div><!-- /.col -->
</section><!-- /.content -->
@endsection
@section('css')
<style type="text/css">
.test-file span {
    font-size: 16px;
    font-weight: lighter;
}

.margin-style {
    margin-top: 40px;
}

.profile_studentheight:120px;
width: 120px;
}

.title-s-data {
    text-decoration: underline;
}

.float-right {
    float: right;
}

.float-left {
    float: left;
}

.color-white {
    color: white;
}

.border {
    box-shadow: 0 0 10px;
    border-bottom: 10px solid green;
}

input[type=text] {
    width: 50%;
}

</style>
@endsection

resources/views/admin/marks/view.blade.php
@extends('layouts.admin.app')
@section('content')
<section class="content">
    <div class="row">
        <div class="col-md-12">
            @include('layouts.alert')
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Show the all Students Marks</h3>
                    <div class="box-body">
                        <div class="col-md-12  ">
                            <div class="row  bg-danger">
                                <form method="post" action="{{route('admin.marks.searchmarks')}}">
                                    @csrf
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <select name="faculty_id" id="faculty" class="form-control">
                                                <option disabled selected>Choose faculty</option>
                                                @foreach($faculty as $data)
                                                <option value="{{$data->faculty_id}}" {{(old('faculty_id')==$data->faculty_id)?'selected':''}} {{isset($faculty_id)?(($faculty_id==$data->faculty_id)?'selected':''):''}}>{{$data->faculty_name}} </option>
                                                @endforeach
                                            </select>
                                            @error('faculty_id')
                                            <small style="color: red">**{{$message}}</small>
                                            @enderror
                                        </div>
                                    </div>
                                 <div class="col-md-2">
                                    <div class="form-group">
                                        <select class="form-control" class="program" name="program_id" id="program">
                                            <option value="0" disabled="true" selected="true">Select Program</option>
                                        </select>
                                        @error('program_id')
                                        <small style="color: red">**{{$message}}</small>
                                        @enderror
                                    </div>
                                </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <select name="year_id" id="year" class="form-control">
                                                <option disabled selected>Choose Year</option>
                                                @foreach($years as $data)
                                                <option value="{{$data->id}}" {{(old('year_id')==$data->id)?'selected':''}} {{isset($year_id)?(($year_id==$data->id)?'selected':''):''}}>{{$data->name}}</option>
                                                @endforeach
                                            </select>
                                            @error('year_id')
                                            <small style="color: red">**{{$message}}</small>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <select name="semester_id" id="semester" class="form-control">
                                                <option disabled selected>Choose semester</option>
                                                @foreach($semesters as $data)
                                                <option value="{{$data->id}}" {{(old('semester_id')==$data->id)?'selected':''}} {{isset($semester_id)?(($semester_id==$data->id)?'selected':''):''}}>{{$data->name}}</option>
                                                @endforeach
                                            </select>
                                            @error('semester_id')
                                            <small style="color: red">**{{$message}}</small>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <select name="admision_year_id" id="admision_year" class="form-control">
                                                <option disabled selected>Admision year</option>
                                                @foreach($admissions as $data)
                                                <option value="{{$data->id}}" {{(old('admision_year_id')==$data->id)?'selected':''}} {{isset($admission_year_id)?(($admission_year_id==$data->id)?'selected':''):''}}>{{$data->admission_year}}</option>
                                                @endforeach
                                            </select>
                                            @error('admision_year_id')
                                            <small style="color: red">**{{$message}}</small>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-md-1">
                                        <button type="submit" class="btn btn-info">Show</button>
                                    </div>
                            </div>
                        </div>
                        </form>
                        <br>
                        @if(isset($flag))
                        <div class="col-md-12 size">
                            <hr>
                            <div style="float:left;" class="left">
                                <p><strong><span>Faculty:</span></strong> {{$SymbolNumberCategory->faculty->faculty_name}} </p>
                                <p><strong><span>Program:</span></strong> {{$SymbolNumberCategory->program->program_name}}</p>
                                <p><strong><span>Admision year:<span></strong>{{$SymbolNumberCategory->admissionyear->admission_year}}</p>
                            </div>
                            <div style="float:right;" class="right">
                                <p><strong><span>Year:<span></strong> {{$SymbolNumberCategory->year->name}}</p>
                                <p><strong><span>Semester:<span></strong> {{$SymbolNumberCategory->semester->name}}</p>
                                <form method="post" action="{{route('admin.marks.edit')}}">
                                    @csrf
                                    <input type="hidden" name="SymbolNumberCategory_id" value="{{$SymbolNumberCategory->id}}">
                                    <button class="btn-primary btn btn-sm" type="submit"> <i class="fa fa-edit "> Edit Marksheet</i></button>
                                </form>
                                <br>
                            </div>
                        </div>
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th style="width: 10px">SN</th>
                                    <th>name</th>
                                    <th>symbol_no</th>
                                    @forelse($subjects as $data)
                                    <th>{{$data->subject_name}}</th>
                                    @empty
                                    <th>no subject</th>
                                    @endforelse
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($symbolNumbers as $symbolNumber)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td> {{$symbolNumber->student->name}}</td>
                                    <td>{{$symbolNumber->symbol_number}}</td>
                                    @forelse($subjects as $subject)
                                    <td>
                                        @forelse($marks as $mark)
                                        @if($mark->subject_id==$subject->id && $mark->symbol_number_id==$symbolNumber->id )
                                        {{ $mark->marks}}
                                        @endif
                                        @empty
                                        @endforelse
                                    </td>
                                    @empty
                                    <td>no subject</td>
                                    @endforelse
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="10">
                                        <center>No data found on this <strong>search</strong> </center>
                                    </td>
                                </tr>
                                @endforelse
                            <tbody>
                        </table>
                        @endif
                    </div><!-- /.box-body -->
                </div>
            </div><!-- /.box -->
        </div><!-- /.col -->
</section><!-- /.content -->
@endsection
@section('css')
<style type="text/css">
.test-file span {
    font-size: 16px;
    font-weight: lighter;
}

.margin-style {
    margin-top: 40px;
}

.profile_student {
    height: 120px;
    width: 120px;
}

.title-s-data {
    text-decoration: underline;
}

</style>
@endsection
@section('script')
   <script type="text/javascript">
    $(document).ready(function(){
  

     $(document).on('change','#faculty',function(){
      var faculty_id=$(this).val();
      var op=" ";
      var div=$(this).parent().parent().parent();

       $.ajax({
            type:'get',
             url: '{!! URL::to('/ajax/getprogram') !!}',
            data:{'id':faculty_id},
            success:function(data){
                  op+='<option value="0" selected disabled>Choose Program</option>';
                  for(var i=0; i<data.length; i++)
                   {
                    op+='<option value="'+data[i].program_id+'">'+data[i].program_name+'</option>';
                   }
                  div.find('#program').html(" ");
                   div.find('#program').append(op);     
            },
            error:function(){
           },
        });
     });
   });
 </script>
@endsection