routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 Route::get('/','admin\LoginController@showloginform')->name('showloginform')->middleware('AuthRedirect');

// Auth::routes();
 Route::post('/login','admin\LoginController@login')->name('admin.login');
 Route::post('/logout','admin\LoginController@logout')->name('admin.logout');

 Route::get('/home', 'HomeController@index')->name('admin.dashboard.home')->middleware('Admin');
 Route::post('/EditProfile/{id}','HomeController@edit')->name('editprofile');

 Route::namespace('admin')->name('admin.')->middleware('Admin')->group(function()
{      
        //Students Routes//
        Route::get('/AddStudents', 'students\studentsController@create')->name('students.create');
        Route::get('/ShowStudents', 'students\studentsController@index')->name('students.index');
        Route::get('/ajax/getprogram','students\studentsController@findprogram');
        Route::post('/Students/store', 'students\studentsController@store')->name('students.store');
        Route::get('/ViewStudents/{student}', 'students\studentsController@view')->name('students.view');
        Route::get('/DeleteStudent/{id}', 'students\studentsController@destroy')->name('students.destroy');
        Route::get('/EditStudent/{id}', 'students\studentsController@edit')->name('students.edit');
        Route::post('/UpdateStudent/{id}', 'students\studentsController@update')->name('students.update');
        Route::post('/SearchStudents','students\studentsController@search')->name('students.search');



        //Notice Routes//
         Route::get('/AddNotice' ,'notice\noticeController@create')->name('notice.create');
         Route::get('/ViewNotices' ,'notice\noticeController@index')->name('notice.index');
         Route::post('PostNotice/store','notice\noticeController@store')->name('notice.store');
         Route::get('/EditNotice/{id}','notice\noticeController@edit')->name('notice.edit');
         Route::post('/UpdateNotice/{id}','notice\noticeController@update')->name('notice.update');
         Route::get('/DeleteNotice/{id}','notice\noticeController@destroy')->name('notice.destroy');


         //Assignment Routes//
         Route::get('/AddAssignment','assignment\assignmentController@create')->name('assignment.create');
         Route::get('/ShowAssignment','assignment\assignmentController@index')->name('assignment.index');
         Route::post('/PostAssignment/store','assignment\assignmentController@store')->name('assignment.store');
         Route::post('/SearchAssignment','assignment\assignmentController@searchassignment')->name('assignment.searchassignment');
         Route::get('/EditAssignment/{id}','assignment\assignmentController@edit')->name('assignment.edit');
         Route::post('/udateAssignment/{id}','assignment\assignmentController@update')->name('assignment.update');
         Route::get('/DeleteAssignment/{id}','assignment\assignmentController@destroy')->name('assignment.destroy');


        //Courses Routes//
        Route::get('/AddCourses','courses\coursesController@create')->name('courses.create');
        Route::get('/ShowCourses','courses\coursesController@index')->name('courses.index');
        Route::post('/StoreCourseCatogery/store','courses\coursesController@store')->name('courses.store');
        Route::post('/SearchCourseCatogey','courses\coursesController@searchtoinsertcourse')->name('courses.searchtoinsertcourse');
        Route::get('/ShowSubjectFields/{id}','courses\coursesController@showsubject')->name('courses.subject');
        Route::post('/StoreSubject/store','courses\coursesController@storesubject')->name('courses.storesubject');
        Route::get('/DeleteSubject/{id}','courses\coursesController@destroy')->name('courses.destroy');



        //Marks Routes//
        Route::get('/ShowMarks','marks\MarksController@searchmarks')->name('marks.view');
        Route::post('ViewMarks','marks\MarksController@viewmarks')->name('marks.searchmarks');
        Route::get('/InsertMarks','marks\MarksController@index')->name('marks.index');
        Route::post('/AddMarks','marks\MarksController@showmarksform')->name('marks.addmarks');
        Route::post('/Store/Marks','marks\MarksController@store')->name('marks.store');
        Route::Post('/EditMarks','marks\MarksController@edit')->name('marks.edit');
        Route::post('/UpdateMarks/Update','marks\MarksController@updatemarks')->name('marks.update');




        //Teachers Routes//
        Route::get('/AddTeachers','Teachers\teachersController@create')->name('teachers.create');
        Route::get('/ShowTeachers','Teachers\teachersController@index')->name('teachers.index');
        Route::post('PostTeachers/store','Teachers\teachersController@store')->name('teachers.store');
        Route::get('Teachers/destroy/{id}','Teachers\teachersController@destroy')->name('teachers.destroy');
        
        //Faculty Routes//
        Route::get('/AddFaculty','faculty\facultyController@create')->name('faculty.create');
        Route::get('/ShowFaculty','faculty\facultyController@index')->name('faculty.index');
        Route::post('/AddFaculty/store','faculty\facultyController@store')->name('faculty.store');
        Route::get('/EditFaculty/{faculty_id}','faculty\facultyController@edit')->name('faculty.edit');
        Route::post('/UpdateFaculty/{faculty_id}','faculty\facultyController@update')->name('faculty.update');
        Route::get('/DeleteFaculty/{faculty_id}','faculty\facultyController@destroy')->name('faculty.destroy');

        //Program Routes//
        Route::get('/AddProgram','program\programController@create')->name('program.create');
        Route::get('/ShowProgram','program\programController@index')->name('program.index');
        Route::post('/AddProgram/store','program\programController@store')->name('program.store');
        Route::get('/EditProgram/{program_id}','program\programController@edit')->name('program.edit');
        Route::post('/UpdateProgram/{program_id}','program\programController@update')->name('program.update');
        Route::get('/DeleteProgram/{program_id}','program\programController@destroy')->name('program.destroy');
        Route::post('/SearchProgram/from/faculty','program\programController@searchprogram')->name('search.program.from.faculty');


        //Symbol Routes//
        Route::get('/AddSymbol','Symbol\SymbolController@create')->name('symbol.create');
        Route::get('/ajax/getprogram','Symbol\SymbolController@findprogram');
        Route::post('/ShowSymbolForm','symbol\SymbolController@symbolnumberform')->name('symbol.showsymbolnumberform');
        Route::post('/SymbolNo/store','symbol\SymbolController@store')->name('symbol.store');
        Route::get('/AllSymbolData','symbol\SymbolController@index')->name('symbol.index');
        Route::post('/SearchSymbolCatogory','symbol\SymbolController@SearhSymbolFaculty')->name('symbol.SearhSymbolFaculty');
        Route::get('/ShowAllSymbol/{symbol_number_category_id}','symbol\SymbolController@symbolview')->name('symbol.viewsymbol');
        Route::get('/EditSymboNumber/{symbol_number_category_id}','symbol\SymbolController@symbolupdate')->name('symbol.symbolupdate');
        Route::post('/UpdateSymbol/store','symbol\SymbolController@symbolupdatestore')->name('symbol.symbolupdatestore');
        

        //Year Routes//
        Route::get('/CreateYear','AdmissionYear\YearController@index')->name('year.index');
        Route::post('/PostYear/store','AdmissionYear\YearController@store')->name('year.store');
        Route::get('/EditYear/{id}','AdmissionYear\YearController@edit')->name('year.edit');
        Route::post('/UpdateYear/{id}','AdmissionYear\YearController@update')->name('year.update');
        Route::get('/DeleteYear/{id}','AdmissionYear\YearController@destroy')->name('year.destroy');


        //user access  and user role control route here
         Route::get('user/role','UserRoleController@index')->name('user.role');
         Route::get('user/role/create','UserRoleController@create')->name('create.user.role');
         Route::post('user/role/store','UserRoleController@store')->name('store.user.role');
         Route::get('user/access/show/{role_id}','UserAccessController@show')->name('show.user.access');
         Route::post('user/access/store','UserAccessController@store')->name('store.user.access');

         //Register for role id password//
         Route::get('user/register','RoleRegisterController@roleregisterform')->name('role.register.form');
         Route::post('user/register/store','RoleRegisterController@store')->name('role.register.store');


});



//FontEnd Page Routes//
Route::get('/EducatSystem','user\UserController@index')->name('user.index');
Route::get('/StudentResult','user\UserController@result')->name('user.result');
Route::post('/MarkSheet/Marks','user\UserController@showmarksheet')->name('user.marksheet');
Route::get('/Notices','user\UserController@notice')->name('user.notice');

app/Notice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notice extends Model
{
  protected $fillable=[
  	'user_id',
  	'notice_title',
  	'date_of_notice',
  	'notice_subject',
  	'description',
  ];
}

app/Http/Controllers/admin/notice/noticeController.php
<?php

namespace App\Http\Controllers\admin\notice;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Notice;
use Auth;

class noticeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $data['notices']=Notice::all();
      return view('admin.notice.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('admin.notice.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'notice_title'=>'required',
            'date_of_notice'=>'required',
            'notice_subject'=>'required',
            'description'=>'required',
        ]);

        $request['user_id']=Auth::id();
      
            

        Notice::Create($request->only(['user_id','notice_title','date_of_notice','notice_subject','description']));
        session()->flash('success','Notice has been sucessfully Published');
        return redirect('/AddNotice');
                    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Notice $id)
    {
      $data['notice']=$id;
      return view('admin.notice.create',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
     $this->validate($request,[
            'notice_title'=>'required',
            'date_of_notice'=>'required',
            'notice_subject'=>'required',
            'description'=>'required',
        ]);
    $data=$request->only(['notice_title','date_of_notice','notice_subject','description']);
    Notice::where('id',$request->id)->update($data);
    session()->flash('success','Notice has been sucessfully Updated');
    return redirect('/ViewNotices');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Notice::where('id',$id)->delete();
        session()->flash('success','Notice has been sucessfully Deleted');
        return redirect('/ViewNotices');
    }
}

resources/views/admin/notice/create.blade.php
@extends('layouts.admin.app')
@section('content')
<!--start content-->
<section class="content">
      <div class='row'>
            <div class='col-md-12'>
              @include('layouts.alert')
                 <div class='box box-primary'>
                     <div class='box-header'>
                      <h3 class='box-title'>{{isset($notice) ? 'Edit Notices' : 'Create Notices'}}</h3>
                      </div><!-- /.box-header -->
                         <div class='box-body'>
                         <form method="post" action="{{isset($notice)? route('admin.notice.update',$notice->id) : route('admin.notice.store')}}">
                          @csrf
                          @if(isset($notice))
                            @method('Post')
                          @endif
                          <div class="row">
                            <div class="col-md-6">
                             <div class="form-group" >
                                <label for="exampleInputnotice">Notice Title</label>
                                <input type="text" class="form-control" name="notice_title" placeholder="Add The Notice Title" value="{{ isset($notice)?$notice->notice_title:''}}">
                             </div>
                            </div>

                            <div class="col-md-6">
                              <div class="form-group">
                                <label for="exampleInputDate">Date of Notice</label>
                                <input type="date" class="form-control" name="date_of_notice" placeholder="Add Date" value="{{isset($notice) ? $notice->date_of_notice : ''}}">
                             </div>
                            </div>

                            <div class="col-md-12">
                            <div class="form-group">
                                <label for="exampleInputsubject">Notice Subject</label>
                                <input type="text" class="form-control" name="notice_subject" placeholder="Add The Notice Subject" value="{{isset($notice) ? $notice->notice_subject : ''}}">
                             </div>
                           </div>
                          </div>

                             <div class="form-group">
                              <label for="exampleInputdescription">Add Description</label>
                              <textarea type="text" class="form-control" placeholder="Add The Notice Description" name="description" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;" value="{{isset($notice) ? $notice->description : ''}}"></textarea>
                             </div> 
                            <div class="box-footer">
                              <center><button type="submit" class="btn btn-primary btn-flat">{{isset($notice) ? 'Update The Notices' : 'Post Notices' }}</button></center>
                            </div> 
                         </form>
                       </div>
                 </div>
            </div><!-- /.col-->
         </div><!-- ./row -->
</section><!-- /.content -->

@endsection
 

resources/views/admin/notice/index.blade.php
@extends('layouts.admin.app')
@section('content')

<section class="content">
        <div class="row">
            <div class="col-md-12">
            	@include('layouts.alert')
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">List of Assignment</h3>
                        <a href="{{ route('admin.notice.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> Create More Notices</a>
                    </div><!-- /.box-header -->
                    <div class="box-body table-responsive">
                        <table id="example1" class="table table-bordered table-striped ">
                          <thead>
                            <tr>
                                <th style="width: 10px">SN</th>
                                <th>Title</th>
                                <th>Date</th>
                                <th>NoticeSubject</th>
                                <th>Description</th>
                                <th style="width: 88px">Action</th>
                            </tr>
                          </thead>

                            <tbody>
                            	@foreach($notices as $row)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$row->notice_title}}</td>
                                    <td>{{$row->date_of_notice}}</td>
                                    <td>{{$row->notice_subject}}</td>
                                    <td>{{$row->description}}</td>
                                    <td>
                                        <a href="{{route('admin.notice.edit',$row->id)}}"> <i class="fa fa-edit btn btn-info btn-sm"></i></a>
                                        <a href="{{route('admin.notice.destroy',$row->id)}}"><i class="fa fa-trash-o btn btn-danger btn-sm"></i></a>
                                    </td>
                                </tr>
                                @endforeach
                            <tbody>
                        </table>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->

            </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
@endsection
 