routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 Route::get('/','admin\LoginController@showloginform')->name('showloginform')->middleware('AuthRedirect');

// Auth::routes();
 Route::post('/login','admin\LoginController@login')->name('admin.login');
 Route::post('/logout','admin\LoginController@logout')->name('admin.logout');

 Route::get('/home', 'HomeController@index')->name('admin.dashboard.home')->middleware('Admin');
 Route::post('/EditProfile/{id}','HomeController@edit')->name('editprofile');

 Route::namespace('admin')->name('admin.')->middleware('Admin')->group(function()
{      
        //Students Routes//
        Route::get('/AddStudents', 'students\studentsController@create')->name('students.create');
        Route::get('/ShowStudents', 'students\studentsController@index')->name('students.index');
        Route::get('/ajax/getprogram','students\studentsController@findprogram');
        Route::post('/Students/store', 'students\studentsController@store')->name('students.store');
        Route::get('/ViewStudents/{student}', 'students\studentsController@view')->name('students.view');
        Route::get('/DeleteStudent/{id}', 'students\studentsController@destroy')->name('students.destroy');
        Route::get('/EditStudent/{id}', 'students\studentsController@edit')->name('students.edit');
        Route::post('/UpdateStudent/{id}', 'students\studentsController@update')->name('students.update');
        Route::post('/SearchStudents','students\studentsController@search')->name('students.search');



        //Notice Routes//
         Route::get('/AddNotice' ,'notice\noticeController@create')->name('notice.create');
         Route::get('/ViewNotices' ,'notice\noticeController@index')->name('notice.index');
         Route::post('PostNotice/store','notice\noticeController@store')->name('notice.store');
         Route::get('/EditNotice/{id}','notice\noticeController@edit')->name('notice.edit');
         Route::post('/UpdateNotice/{id}','notice\noticeController@update')->name('notice.update');
         Route::get('/DeleteNotice/{id}','notice\noticeController@destroy')->name('notice.destroy');


         //Assignment Routes//
         Route::get('/AddAssignment','assignment\assignmentController@create')->name('assignment.create');
         Route::get('/ShowAssignment','assignment\assignmentController@index')->name('assignment.index');
         Route::post('/PostAssignment/store','assignment\assignmentController@store')->name('assignment.store');
         Route::post('/SearchAssignment','assignment\assignmentController@searchassignment')->name('assignment.searchassignment');
         Route::get('/EditAssignment/{id}','assignment\assignmentController@edit')->name('assignment.edit');
         Route::post('/udateAssignment/{id}','assignment\assignmentController@update')->name('assignment.update');
         Route::get('/DeleteAssignment/{id}','assignment\assignmentController@destroy')->name('assignment.destroy');


        //Courses Routes//
        Route::get('/AddCourses','courses\coursesController@create')->name('courses.create');
        Route::get('/ShowCourses','courses\coursesController@index')->name('courses.index');
        Route::post('/StoreCourseCatogery/store','courses\coursesController@store')->name('courses.store');
        Route::post('/SearchCourseCatogey','courses\coursesController@searchtoinsertcourse')->name('courses.searchtoinsertcourse');
        Route::get('/ShowSubjectFields/{id}','courses\coursesController@showsubject')->name('courses.subject');
        Route::post('/StoreSubject/store','courses\coursesController@storesubject')->name('courses.storesubject');
        Route::get('/DeleteSubject/{id}','courses\coursesController@destroy')->name('courses.destroy');



        //Marks Routes//
        Route::get('/ShowMarks','marks\MarksController@searchmarks')->name('marks.view');
        Route::post('ViewMarks','marks\MarksController@viewmarks')->name('marks.searchmarks');
        Route::get('/InsertMarks','marks\MarksController@index')->name('marks.index');
        Route::post('/AddMarks','marks\MarksController@showmarksform')->name('marks.addmarks');
        Route::post('/Store/Marks','marks\MarksController@store')->name('marks.store');
        Route::Post('/EditMarks','marks\MarksController@edit')->name('marks.edit');
        Route::post('/UpdateMarks/Update','marks\MarksController@updatemarks')->name('marks.update');




        //Teachers Routes//
        Route::get('/AddTeachers','Teachers\teachersController@create')->name('teachers.create');
        Route::get('/ShowTeachers','Teachers\teachersController@index')->name('teachers.index');
        Route::post('PostTeachers/store','Teachers\teachersController@store')->name('teachers.store');
        Route::get('Teachers/destroy/{id}','Teachers\teachersController@destroy')->name('teachers.destroy');
        
        //Faculty Routes//
        Route::get('/AddFaculty','faculty\facultyController@create')->name('faculty.create');
        Route::get('/ShowFaculty','faculty\facultyController@index')->name('faculty.index');
        Route::post('/AddFaculty/store','faculty\facultyController@store')->name('faculty.store');
        Route::get('/EditFaculty/{faculty_id}','faculty\facultyController@edit')->name('faculty.edit');
        Route::post('/UpdateFaculty/{faculty_id}','faculty\facultyController@update')->name('faculty.update');
        Route::get('/DeleteFaculty/{faculty_id}','faculty\facultyController@destroy')->name('faculty.destroy');

        //Program Routes//
        Route::get('/AddProgram','program\programController@create')->name('program.create');
        Route::get('/ShowProgram','program\programController@index')->name('program.index');
        Route::post('/AddProgram/store','program\programController@store')->name('program.store');
        Route::get('/EditProgram/{program_id}','program\programController@edit')->name('program.edit');
        Route::post('/UpdateProgram/{program_id}','program\programController@update')->name('program.update');
        Route::get('/DeleteProgram/{program_id}','program\programController@destroy')->name('program.destroy');
        Route::post('/SearchProgram/from/faculty','program\programController@searchprogram')->name('search.program.from.faculty');


        //Symbol Routes//
        Route::get('/AddSymbol','Symbol\SymbolController@create')->name('symbol.create');
        Route::get('/ajax/getprogram','Symbol\SymbolController@findprogram');
        Route::post('/ShowSymbolForm','symbol\SymbolController@symbolnumberform')->name('symbol.showsymbolnumberform');
        Route::post('/SymbolNo/store','symbol\SymbolController@store')->name('symbol.store');
        Route::get('/AllSymbolData','symbol\SymbolController@index')->name('symbol.index');
        Route::post('/SearchSymbolCatogory','symbol\SymbolController@SearhSymbolFaculty')->name('symbol.SearhSymbolFaculty');
        Route::get('/ShowAllSymbol/{symbol_number_category_id}','symbol\SymbolController@symbolview')->name('symbol.viewsymbol');
        Route::get('/EditSymboNumber/{symbol_number_category_id}','symbol\SymbolController@symbolupdate')->name('symbol.symbolupdate');
        Route::post('/UpdateSymbol/store','symbol\SymbolController@symbolupdatestore')->name('symbol.symbolupdatestore');
        

        //Year Routes//
        Route::get('/CreateYear','AdmissionYear\YearController@index')->name('year.index');
        Route::post('/PostYear/store','AdmissionYear\YearController@store')->name('year.store');
        Route::get('/EditYear/{id}','AdmissionYear\YearController@edit')->name('year.edit');
        Route::post('/UpdateYear/{id}','AdmissionYear\YearController@update')->name('year.update');
        Route::get('/DeleteYear/{id}','AdmissionYear\YearController@destroy')->name('year.destroy');


        //user access  and user role control route here
         Route::get('user/role','UserRoleController@index')->name('user.role');
         Route::get('user/role/create','UserRoleController@create')->name('create.user.role');
         Route::post('user/role/store','UserRoleController@store')->name('store.user.role');
         Route::get('user/access/show/{role_id}','UserAccessController@show')->name('show.user.access');
         Route::post('user/access/store','UserAccessController@store')->name('store.user.access');

         //Register for role id password//
         Route::get('user/register','RoleRegisterController@roleregisterform')->name('role.register.form');
         Route::post('user/register/store','RoleRegisterController@store')->name('role.register.store');


});



//FontEnd Page Routes//
Route::get('/EducatSystem','user\UserController@index')->name('user.index');
Route::get('/StudentResult','user\UserController@result')->name('user.result');
Route::post('/MarkSheet/Marks','user\UserController@showmarksheet')->name('user.marksheet');
Route::get('/Notices','user\UserController@notice')->name('user.notice');

app/Program.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Faculty;

class Program extends Model
{
 protected $primarykey="faculty_id";
       protected $fillable = [
          'program_name',
          'faculty_id'
        ];
        
    public function faculty(){
    return $this->belongsTo(Faculty::class,'faculty_id','faculty_id');}

    public function student(){
    return $this->hasMany(Student::class,'program_id','program_id');}

    public function SymbolNumberCategory(){
    return $this->hasMany(SymbolNumberCategory::class);}

    public function CourseCatogery(){
    return $this->hasOne(CourseCatogery::class);}
}

app/Http/Controllers/admin/program/programController.php
<?php

namespace App\Http\Controllers\admin\program;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Faculty;
use App\Program;
use Illuminate\Validation\Rule;


class programController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {

       $data['program']=Program::all();
       $data['faculty']=Faculty::all();
       return view('admin.program.index',$data);
    }

    public function searchprogram(Request $request)
    {
      $this->validate($request,[
        'faculty_id'=>'required',
      ]);

    $data['program']=Program::where('faculty_id',$request->faculty_id)->get();
    $data['faculty']=Faculty::all();
    return view('admin.program.index',$data);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       $data['faculty']=Faculty::all();
       return view('admin.program.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'program_name'=>'required',
            'faculty_id'=>'required',

        ]);
            Program::create([
            'program_name' => $request->program_name,
            'faculty_id' => $request->faculty_id
            ]);
        return redirect('/ShowProgram')->with('success', 'Program Added  Sucessfully Done');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($program_id)
    {  
       $data['program']=Program::where('program_id',$program_id)->first();
       $data['faculty']=Faculty::all();
       return view('admin.program.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $program_id)
    {
        $this->validate($request,[
            'program_name'=>['required' ,Rule::unique('programs','program_name')->ignore($request->program_id, 'program_id')],
            ],

          [
            'program_name.unique'=>'Program Name Must Be unique Name',
          ]);

        // $this->validate($data,$rule,$message);//to validate Form Message By Own Custome Error Message

        $data['program_name']=$request->program_name;
        $data['faculty_id']=$request->faculty_id;
        Program::where('program_id',$request->program_id)->update($data);
        return redirect('/ShowProgram')->with('success', 'Program Update Sucessfully Done');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($program_id)
    {
     Program::where('program_id',$program_id)->delete();
     return redirect('/ShowProgram')->with('success', 'Program Delete Sucessfully Done');
    }
}

resources/views/admin/Program/create.blade.php
@extends('layouts.admin.app')
@section('content')

                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title">Insert The Faculties</h3>
                                </div><!-- /.box-header -->
                                <!-- form start -->
                            <div class="box-body">
                                <form role="form" method="post" action="{{route('admin.program.store')}}">                    
                                    {{csrf_field()}}                 
                                     <div class="col-md-12">
                                         <div class="form-group">
                                            <label for="exampleInputProgram">Program Name</label>
                                            <input type="text" class="form-control" name="program_name" placeholder="Enter Program Name">
                                        </div>
                                        <div class="form-group">
                                            <label>Faculty</label>
                                            <select class="form-control" name="faculty_id">
                                            <option selected disabled>---choose faculty---</option>
                                               @foreach($faculty as $faculty)
                                                <option value="{{ $faculty->faculty_id}}">{{ $faculty->faculty_name}}</option>
                                               @endforeach
                                            </select>
                                        </div>
                                     </div>

                                    <div class="box-footer">
                                        <center><button type="submit" class="btn btn-primary btn-flat" name="course_data">Submit Faculty</button></center>
                                    </div>
                                </form>
                              </div><!-- /.box-body -->
                            </div><!-- /.box -->

                            <!-- Form Element sizes -->
                    </div>   <!-- /.row -->
                </section><!-- /.content -->

@endsection
 

resources/views/admin/Program/edit.blade.php
@extends('layouts.admin.app')
@section('content')

                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title">Insert The Faculties</h3>
                                </div><!-- /.box-header -->
                                <!-- form start -->
                            <div class="box-body">
                                <form role="form" method="post" action="{{ route('admin.program.update',$program->program_id)}}">                    
                                    {{csrf_field()}}                 
                                     <div class="col-md-12">
                                         <div class="form-group">
                                            <label for="exampleInputProgram">Program Name</label>
                                            <input type="text" class="form-control" name="program_name" placeholder="Enter Program Name" value="{{$program->program_name }}">
                                           @error('program_name')
                                             <span class="invalid-feedback" role="alert">
                                             <strong style="color: red;">*{{ $message }}*</strong>
                                            </span>
                                            @enderror
                                        </div>
                                        <div class="form-group">
                                            <label>Faculty</label>
                                            <select class="form-control" name="faculty_id">
                                            <option selected disabled>---choose faculty---</option>
                                               @foreach($faculty as $data)
                                                 <option value="{{ $data->faculty_id}}" 

                                                    @if($data->faculty_id==$program->faculty_id)
                                                     selected 
                                                    @else

                                                    @endif
                                                    >{{$data->faculty_name}}</option>
                                               @endforeach                                            
                                            </select>

                                        </div>
                                     </div>

                                    <div class="box-footer">
                                        <center><button type="submit" class="btn btn-primary btn-flat" name="course_data">Submit Faculty</button></center>
                                    </div>
                                </form>
                              </div><!-- /.box-body -->
                            </div><!-- /.box -->

                            <!-- Form Element sizes -->
                    </div>   <!-- /.row -->
                </section><!-- /.content -->

@endsection
 

resources/views/admin/Program/index.blade.php
@extends('layouts.admin.app')
@section('content')

@php

$session_role=session('UserAccess');

@endphp

<section class="content">
        <div class="row">
            <div class="col-md-12">
           @include('layouts.alert')
                 <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">List of Program</h3>
                        @if(array_key_exists('3_add',$session_role))
                         @if($session_role['3_add']==1)
                        <a href="{{route('admin.program.create')}}" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> Create More</a>
                        @endif
                        @endif
                    </div><!-- /.box-header -->
                    <div class="box-body table-responsive">

                    <form method="post" action="{{route('admin.search.program.from.faculty')}}">
                        @csrf
                        <div class="form-group">
                        <label>Find The Program According To Faculty </label><br>
                        <div style="width: 100%;" class="float">
                          <div style="float: left; width: 92%;" class="left">
                             <select class="form-control" name="faculty_id">
                                 <option disabled selected>--Select faculty--</option>
                                  @foreach($faculty as $data)
                                    <option value="{{$data->faculty_id}}">{{$data->faculty_name}} </option>
                                  @endforeach 
                            </select><br>
                        </div>
                        <div style="float:right; margin-right:20px;" class="right">
                            <button type="submit" class="btn btn-info btn-sm ">Search</button>
                        </div>
                      </div>
                 </div>
              </form>
                        <table class="table table-bordered table-striped">
                           <thead> 
                            <tr>
                                <th style="width: 10px">SN</th>
                                <th>Program Name</th>
                                <th>Faculty Name</th>

                                @if(array_key_exists('3_view',$session_role))
                                @if($session_role['3_edit']==1 ||$session_role['3_delete']==1 )
                                <th style="width: 88px">Action</th>
                                @endif
                                @endif
                            </tr>
                          </thead>
                           <tbody>
                            @foreach($program as $data)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$data->program_name}}</td>
                                    <td>{{$data->faculty->faculty_name}}</td>

                                     @if(array_key_exists('3_view',$session_role))
                                     @if($session_role['3_edit']==1 || $session_role['3_delete']==1)
                                    <td>
                                        @if($session_role['3_edit']==1 )
                                        <a href="{{route('admin.program.edit',$data->program_id)}}"> <i class="fa fa-edit btn btn-info btn-sm"></i></a>
                                        @endif

                                        @if($session_role['3_delete']==1)
                                        <a href="{{route('admin.program.destroy',$data->program_id)}}"><i class="fa fa-trash-o btn btn-danger btn-sm"></i></a>
                                        @endif
                                    </td>

                                     @endif
                                     @endif
                                </tr>
                                @endforeach
                           <tbody>
                        </table>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->

            </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->

@endsection